export enum ACTION_INDEXES {
  Goto = 0,
  Label = 1,
  Popup = 2,
  Transparency = 3,
  VisibilityRange = 4,
  Information = 5,
  ChangeSymbol = 6,
  Solo = 7,
  Flash = 8,
  CopyUrl = 9,
  Refresh = 10,
  Details = 11,
  Spotlight = 13,
  ClearSpotlight = 14,
  MoveTop = 15,
  MoveBottom = 16,
  MoveOut = 17,
  Remove = 18,
  Option = 100
}
